chore: dev server를 https로 start하는 코드 추가 (SP-668)

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -50,13 +50,18 @@ jobs:
         run: |
           yarn build
 
-      - name: Run Lighthouse CI
+      - name: Start server with HTTPS
         env:
           HOST: local.ludo.study
           HTTPS: true
           SSL_CRT_FILE: cert/local.ludo.study.pem
           SSL_KEY_FILE: cert/local.ludo.study-key.pem
+        run: |
+          yarn start:mac
+
+      - name: Run Lighthouse CI
+        env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
         run: |
           yarn global add @lhci/cli
-          lhci autorun --chrome-flags="--ignore-certificate-errors"|| echo "Fail to Run Lighthouse CI!"
+          lhci autorun || echo "Fail to Run Lighthouse CI!"
