chore: certificate error ignore flag 설정 (SP-668)

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -58,13 +58,5 @@ jobs:
           SSL_KEY_FILE: cert/local.ludo.study-key.pem
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
         run: |
-          ## Print Environment Variables
-          echo "HOST: $HOST"
-          echo "HTTPS: $HTTPS"
-          echo "SSL_CRT_FILE: $SSL_CRT_FILE"
-          echo "SSL_KEY_FILE: $SSL_KEY_FILE"
-          echo "LHCI_GITHUB_APP_TOKEN: $LHCI_GITHUB_APP_TOKEN"
-
-
           yarn global add @lhci/cli
-          lhci autorun --verbose || echo "Fail to Run Lighthouse CI!"
+          lhci autorun --chrome-flags="--ignore-certificate-errors"|| echo "Fail to Run Lighthouse CI!"
